<?xml version="1.0" encoding="utf-8"?><Database Name="QLSinhVien" Class="dbQLSinhVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-SSSL7QM;Initial Catalog=QLSinhVien;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLSinhVienConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HEDAOTAO" Member="HEDAOTAOs">
    <Type Name="HEDAOTAO">
      <Column Name="MaHDT" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHDT" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="HEDAOTAO_LOP" Member="LOPs" ThisKey="MaHDT" OtherKey="MaHDT" Type="LOP" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KHOA_LOP" Member="LOPs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="LOP" />
      <Association Name="KHOA_SINHVIEN" Member="SINHVIENs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.KHOAHOC" Member="KHOAHOCs">
    <Type Name="KHOAHOC">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KHOAHOC_LOP" Member="LOPs" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="LOP" />
      <Association Name="KHOAHOC_SINHVIEN" Member="SINHVIENs" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="SINHVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="LOP_SINHVIEN" Member="SINHVIENs" ThisKey="MaLop" OtherKey="MaLop" Type="SINHVIEN" />
      <Association Name="HEDAOTAO_LOP" Member="HEDAOTAO" ThisKey="MaHDT" OtherKey="MaHDT" Type="HEDAOTAO" IsForeignKey="true" />
      <Association Name="KHOA_LOP" Member="KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="KHOA" IsForeignKey="true" />
      <Association Name="KHOAHOC_LOP" Member="KHOAHOC" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="KHOAHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChuyenNganh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NoiThuongTru" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="SINHVIEN_TAIKHOAN" Member="TAIKHOAN" ThisKey="MaSV" OtherKey="TenDN" Type="TAIKHOAN" Cardinality="One" />
      <Association Name="SINHVIEN_DIEM" Member="DIEMs" ThisKey="MaSV" OtherKey="MaSV" Type="DIEM" />
      <Association Name="KHOA_SINHVIEN" Member="KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="KHOA" IsForeignKey="true" />
      <Association Name="KHOAHOC_SINHVIEN" Member="KHOAHOC" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="KHOAHOC" IsForeignKey="true" />
      <Association Name="LOP_SINHVIEN" Member="LOP" ThisKey="MaLop" OtherKey="MaLop" Type="LOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TenDN" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="SINHVIEN_TAIKHOAN" Member="SINHVIEN" ThisKey="TenDN" OtherKey="MaSV" Type="SINHVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MONHOC" Member="MONHOCs">
    <Type Name="MONHOC">
      <Column Name="MaMH" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MONHOC_DIEM" Member="DIEMs" ThisKey="MaMH" OtherKey="MaMH" Type="DIEM" />
    </Type>
  </Table>
  <Table Name="dbo.DIEM" Member="DIEMs">
    <Type Name="DIEM">
      <Column Name="Stt" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemLan1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemLan2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemTB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MONHOC_DIEM" Member="MONHOC" ThisKey="MaMH" OtherKey="MaMH" Type="MONHOC" IsForeignKey="true" />
      <Association Name="SINHVIEN_DIEM" Member="SINHVIEN" ThisKey="MaSV" OtherKey="MaSV" Type="SINHVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="Username" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>